const CATALOGO = {
  "DEREK'S": [
    {
      "id": "brian-o-conner",
      "name": "BRIAN O´CONNER",
      "type": "Playera",
      "price": 449,
      "old_price": 599,
      "wholesale_price": 399,
      "wholesale_min_qty": 6,
      "stock": 5,
      "sizes": [
        "CH",
        "M",
        "G",
        "XL"
      ],
      "image": "assets/boc.png",
      "badge": "DEREK'S",
      "desc": "ICONICA PLAYERA DE BRIAN EN 2FAST 2FURIOUS."
    },
    {
      "id": "hdfu",
      "name": "HDFU",
      "type": "Playera",
      "price": 499,
      "old_price": 599,
      "wholesale_price": 425,
      "wholesale_min_qty": 6,
      "stock": 5,
      "sizes": [
        "CH",
        "M",
        "G",
        "XL"
      ],
      "image": "assets/ddd.png",
      "badge": "DEREK'S",
      "desc": "FULLBACK JESUS CON CORONA."
    },
    {
      id: "pasamontañas_cadena",
      name: "MASK",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 425,
      wholesale_min_qty: 6,
      stock: 8,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-mask-tee.png",
      badge: "Nuevo",
      featured: true,
      desc: "FULLBACK PASAMONTAÑAS Y CADENA."
    },
    {
      id: "dereks-sacrifice-gold",
      name: "SACRIFICED GOLD",
      type: "Playera",
      price: 529,
      old_price: 629,
      wholesale_price: 449,
      wholesale_min_qty: 6,
      stock: 6,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-sacrifice-gold.png",
      badge: "DEREK'S",
      featured: true,
      desc: "SACRIFICE GOLD"
    },
    {
      id: "dereks-not-ashamed",
      name: "NOT ASHAMED",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 425,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-not-ashamed.png",
      badge: "DEREK'S",
      featured: true,
      desc: "DISEÑO FULLBACK BYN."
    },
    {
      id: "dereks-king-of-kings1",
      name: "KING OF KINGS 1",
      type: "Playera",
      price: 529,
      old_price: 629,
      wholesale_price: 449,
      wholesale_min_qty: 6,
      stock: 4,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-king-of-kings.png",
      badge: "DEREK'S",
      featured: true,
      desc: "JESUS CARGANDO LA CRUZ BYN."
    },
    {
      id: "dereks-sacrifice-byn",
      name: "SACRIFICE BYN",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 425,
      wholesale_min_qty: 6,
      stock: 3,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-sacrifice-white.png",
      badge: "DEREK'S",
      featured: false,
      desc: "FULLBACK SACRIFICE BYN."
    },
    {
      id: "dereks-oveja-100",
      name: "LA 100",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 425,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-oveja-perdida.png",
      badge: "DEREK'S",
      featured: false,
      desc: "FULLBACK OVEJA 100."
    },
    {
      id: "dereks-almighty",
      name: "ALMIGHTY",
      type: "Playera",
      price: 529,
      old_price: 629,
      wholesale_price: 449,
      wholesale_min_qty: 6,
      stock: 4,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/dereks-crucifixion-art.png",
      badge: "DEREK'S",
      featured: false,
      desc: "JESUS CON CORONA ALMIGHTY."
    }
  ],

  "BOSS": [
     {
      id: "boss-negra-1",
      name: "BOSS NEGRA 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-25-pm-2.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS NEGRA 1"
    },
    {
      id: "boss-blanca-bordada-oro1",
      name: "BOSS BLANCA BORDADA ORO1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-26-pm-1.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS BLANCA BORDADA ORO"
    },
    {
      id: "boss-negra-bordada-oro1",
      name: "BOSS NEGRA BORDADA ORO1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-26-pm.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "Descripción corta del producto."
    },
    {
      id: "boss-negra-2",
      name: "BOSS NEGRA 2",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-28-pm-2.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS NEGRA LOGO PEQUEÑO"
    },
    {
      id: "boss-blanca-2",
      name: "BOSS BLANCA 2",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-28-pm.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS BLANCA 2"
    },
    {
      id: "boss-verde-1",
      name: "BOSS VERDE 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-23-pm-1.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS VERDE 1"
    },
    {
      id: "boss-beige-1",
      name: "BOSS BEIGE 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-23-pm.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS VERDE 1"
    },
    {
      id: "boss-azul-1",
      name: "BOSS AZUL 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-24-pm-1.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS AZUL LOGO PEQUEÑO"
    },
    {
      id: "boss-negra-3",
      name: "BOSS NEGRA 3",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-24-pm.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS NEGRA 3"
    },
    {
      id: "boss-negra-4",
      name: "BOSS NEGRA 4",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/whatsapp-image-2026-03-25-at-10-26-25-pm-1.jpeg",
      badge: "BOSS",
      featured: false,
      desc: "BOSS NEGRA 4"
    }    
  ],

  "HUGO": [
        {
      id: "hugo-azul-1",
      name: "HUGO AZUL 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/hugoazul1.jpeg",
      badge: "HUGO",
      featured: false,
      desc: "HUGO AZUL 1"
    },
    {
      id: "hugo-blanca-1",
      name: "HUGO BLANCA 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/hugoblanca1.jpeg",
      badge: "HUGO",
      featured: false,
      desc: "HUGO BLANCA 1"
    },
    {
      id: "hugo-negra-1",
      name: "HUGO NEGRA 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/hugonegra1.jpeg",
      badge: "HUGO",
      featured: false,
      desc: "HUGO NEGRA 1"
    },
    {
      id: "hugo-negra-2",
      name: "HUGO NEGRA 2",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/hugonegra2.jpeg",
      badge: "HUGO",
      featured: false,
      desc: "HUGO NEGRA 2"
    },
    {
      id: "hugo-roja-1",
      name: "HUGO ROJA 1",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 400,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/hugoroja1.jpeg",
      badge: "HUGO",
      featured: false,
      desc: "HUGO ROJA 1"
    },
    {
      id: "hugo-roja-2",
      name: "HUGO ROJA 2",
      type: "Playera",
      price: 499,
      old_price: 599,
      wholesale_price: 425,
      wholesale_min_qty: 6,
      stock: 5,
      sizes: ["CH", "M", "G", "XL"],
      image: "assets/hugoroja2.jpeg",
      badge: "HUGO",
      featured: false,
      desc: "HUGO ROJA 2"
    }
  ],

  "Essentials": [
  ]

};
